---
permalink: online-help/reference-backup-settings-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: Im Dialogfeld Backup-Einstellungen können Sie einen Backup-Pfad und die Anzahl der Aufbewahrung angeben und einen Backup-Zeitplan für eine ausgewählte Unified Manager-Instanz aktivieren. 
---
= Dialogfeld „Backup-Einstellungen“
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Im Dialogfeld Backup-Einstellungen können Sie einen Backup-Pfad und die Anzahl der Aufbewahrung angeben und einen Backup-Zeitplan für eine ausgewählte Unified Manager-Instanz aktivieren.

Sie können die folgenden Datenbank-Backup-Einstellungen ändern:

* *Pfad*
+
Gibt den Pfad zum Speicherort der Sicherungsdateien an. Die folgende Tabelle gibt das Format des Backup-Pfads und die Standardstandorte für verschiedene Betriebssysteme an:

+
[cols="1a,1a"]
|===
| Host-Betriebssystem | Format des Backup-Pfads 


 a| 
Virtuelle Appliance
 a| 
`/opt/netapp/data/ocum-backup`



 a| 
Red hat Enterprise Linux oder CentOS
 a| 
`/data/ocum-backup`



 a| 
Microsoft Windows
 a| 
`C:\ProgramData\NetApp\OnCommandAppData\ocum\backup\`

|===
* *Anzahl Der Einbehalt*
+
Gibt die maximale Anzahl von Backups an, die von Unified Manager beibehalten werden sollen. Der Standardwert ist zehn.

* *Tagesablauf*
+
Gibt den täglichen Backup-Zeitplan mit der Zeit an.

* *Geplante Woche*
+
Gibt den wöchentlichen Backup-Zeitplan mit dem Tag und der Uhrzeit an.

* *Keine*
+
Gibt an, dass keine Backups erstellt werden.





== Befehlsschaltflächen

* *Anwenden*
+
Speichert die Sicherungsdatei und schließt das Dialogfeld. Unified Manager speichert die Sicherungsdatei im folgenden Format: `um_um_version_backup_os_timestamp.7z`.


