---
settings:
  name: Active IQ Unified Manager 9.7
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - name: Unified Manager
    url: "/active-iq-unified-manager-97"
    version-number: '9.7'
  - name: Unified Manager
    url: "/active-iq-unified-manager-99"
    version-number: '9.9'
  - name: Unified Manager
    url: "/active-iq-unified-manager-98"
    version-number: '9.8'
  - name: Unified Manager
    url: "/oncommand-unified-manager-95"
    version-number: '9.5'
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Active IQ Unified Manager 9.7 Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    url: "/release-notes.html"
  - title: Los geht's
    entries:
    - title: Schnellstartinstallation für VMware vSphere
      url: "/install-vapp/qsg-vapp.html"
    - title: Schnellstartinstallation für Linux
      url: "/install-linux/qsg-linux.html"
    - title: Schnellstartinstallation für Windows
      url: "/install-windows/qsg-windows.html"
  - section: install-vapp
  - section: install-linux
  - section: install-windows
  - section: config
  - section: online-help
  - section: performance-checker
  - section: health-checker
  - section: data-protection
  - section: reporting
  - section: api-automation
  - title: Rechtliche Hinweise
    url: "/reference-legal-notices.html"
homepage:
  tiles:
  - title: Los geht's
    links:
    - title: Versionshinweise
      url: "/release-notes.html"
    - title: Schnellstartinstallation für VMware vSphere
      url: "/install-vapp/qsg-vapp.html"
    - title: Schnellstartinstallation für Linux
      url: "/install-linux/qsg-linux.html"
    - title: Schnellstartinstallation für Windows
      url: "/install-windows/qsg-windows.html"
  - title: Installation Konfiguration von Unified Manager
    links:
    - title: Installieren Sie das Upgrade auf VMware vSphere Systemen
      url: "/install-vapp/concept-requirements-for-installing-unified-manager.html"
    - title: Upgrade auf Linux-Systemen installieren
      url: install-linux/concept-requirements-for-installing-unified-manager.html
    - title: Installieren Sie das Upgrade auf Windows-Systemen
      url: "/install-windows/concept-requirements-for-installing-unified-manager.html"
    - title: Konfiguration Von Unified Manager
      url: "/config/concept-configuring-unified-manager.html"
  - title: Performance Monitoring
    links:
    - title: Performance-Schwellenwerte
      url: "/performance-checker/concept-managing-performance-thresholds.html"
    - title: Cluster-Performance
      url: performance-checker/concept-monitoring-cluster-performance-from-the-dashboard.html
    - title: QoS-Richtliniengruppe
      url: "/performance-checker/concept-managing-performance-using-qos-policy-group-information.html"
    - title: Workload Analyzer
      url: "/performance-checker/concept-troubleshooting-workloads-using-the-workload-analyzer.html"
    - title: Workload-Performance
      url: "/performance-checker/concept-collecting-data-and-monitoring-workload-performance.html"
    - title: Performance-Management
      url: performance-checker/concept-managing-performance-using-perf-capacity-and-available-iops-information.html
  - title: Monitoring des Storage- und Objektstatus
    links:
    - title: Cluster und Cluster-Objektstatus
      url: online-help/concept-managing-and-monitoring-clusters-and-cluster-object-health.html
    - title: Systemzustandsschwellenwerte
      url: "/health-checker/concept-managing-health-thresholds.html"
    - title: Senden Sie AutoSupport-Meldungen und Support-Bundles
      url: health-checker/task-send-a-support-bundle-to-technical-support.html
  - title: Monitoring der Datensicherung
    links:
    - title: Sicherungsbeziehung einrichten
      url: "/data-protection/task-setting-up-protection-relationships-in-unified-manager.html"
    - title: Führen Sie Failover und Failback durch
      url: data-protection/task-performing-a-protection-relationship-failover-and-failback.html
    - title: Sicherungsbeziehung managen
      url: data-protection/concept-managing-and-monitoring-protection-relationships.html
    - title: Berichte generieren
      url: "/reporting/concept-unified-manager-reporting.html"
  - title: Verwendung VON REST-APIs
    links:
    - title: Los geht's
      url: "/api-automation/concept-api-url-and-categories.html"
    - title: Management von Storage-Objekten
      url: "/api-automation/concept-data-center-apis.html"
    - title: Greifen Sie auf ONTAP-APIs zu
      url: "/api-automation/concept-gateway-apis.html"
    - title: Typische Workflows
      url: "/api-automation/concept-workflow-intro.html"
    - title: Bereitstellung von Storage
      url: api-automation/concept-provisioning-workflow.html
  - title: Mehr Ressourcen
    links:
    - title: Unified Manager Videos
      url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7mp3jFSg0IJgo3oeDQRY-Gl
    - title: Unified Manager Blogs
      url: https://www.netapp.com/blog/#q=active%20iq%20unified%20manager&t=Blogs&sort=%40publish_date_mktg%20descending&layout=card&f:@facet_language_mktg=[English]
    - title: Dokumentation für die neueste Version von Active IQ Unified Manager
      url: https://docs.netapp.com/us-en/active-iq-unified-manager/index.html
