---
permalink: api-automation/concept-data-center-apis.html 
sidebar: sidebar 
keywords:  
summary: Die REST-APIs unter der Datacenter-Kategorie liefern Informationen über die Cluster, Nodes, Aggregate, Volumes, LUNs. Fileshares, Namespaces und andere Elemente in Ihrem Datacenter. Diese APIs sind für das Abfragen, Hinzufügen, Löschen oder Ändern der Konfiguration in Ihrem Datacenter verfügbar. 
---
= APIs für das Management von Datacentern
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die REST-APIs unter `datacenter` Kategorie stellt Informationen über die Cluster, Nodes, Aggregate, Volumes, LUNs, Fileshares, Namespaces und andere Elemente in Ihrem Datacenter. Diese APIs sind für das Abfragen, Hinzufügen, Löschen oder Ändern der Konfiguration in Ihrem Datacenter verfügbar.

Die meisten dieser APIs sind GET-Aufrufe, die Cluster-übergreifende Aggregation mit Filter-, Sortier- und Paginierungsunterstützung bieten. Wenn sie diese APIs ausführen, geben sie Daten aus der Datenbank zurück. Daher müssen die neu erstellten Objekte durch den nächsten Erfassungszyklus entdeckt werden, damit sie in der Antwort angezeigt werden.

Wenn Sie die Details eines bestimmten Objekts abfragen möchten, müssen Sie die eindeutige ID dieses Objekts eingeben, um dessen Details anzuzeigen. Beispiel:

[listing]
----
curl -X GET "https://<hostname>/api/datacenter/cluster/clusters/4c6bf721-2e3f-11e9-a3e2-00a0985badbb" -H "accept: application/json" -H "Authorization: Basic <Base64EncodedCredentials>"
----
[NOTE]
====
Die CURL-Befehle, Beispiele, Anfragen und Antworten auf die APIs sind auf Ihrer Swagger API-Schnittstelle verfügbar. Sie können die Ergebnisse nach bestimmten Parametern filtern und sortieren, wie auf Swagger angegeben. Diese APIs ermöglichen die Filterung der Ergebnisse nach spezifischen Storage-Objekten wie Cluster, Volume oder Storage VM.

====
[cols="1a,1a,4a"]
|===
| HTTP-Verb | Pfad | Beschreibung 


 a| 
`GET`
 a| 
`/datacenter/cluster/clusters`

`/datacenter/cluster/clusters/{key}`
 a| 
Mit dieser Methode können Sie Details zu den ONTAP Clustern im gesamten Datacenter anzeigen.



 a| 
`GET`
 a| 
`/datacenter/cluster/nodes`

`/datacenter/cluster/nodes/{key}`
 a| 
Mit dieser Methode können Sie die Details der Nodes im Datacenter anzeigen.



 a| 
`GET`
 a| 
`/datacenter/protocols/cifs/shares`

`/datacenter/protocols/cifs/shares/{key}`
 a| 
Mit dieser Methode können Sie Details zu den CIFS-Freigaben im Datacenter anzeigen.



 a| 
`GET`
 a| 
`/datacenter/protocols/nfs/export-policies`

`/datacenter/protocols/nfs/export-policies/{key}`
 a| 
Sie können diese Methode verwenden, um die Details der Exportrichtlinien für die unterstützten NFS-Dienste anzuzeigen.

Sie können die Exportrichtlinien für eine Cluster- oder Storage-VM abfragen und den Richtlinienschlüssel für den Export zur Bereitstellung von NFS-Dateifreigaben verwenden. Weitere Informationen über das Zuweisen und erneute Verwenden von Exportrichtlinien für Workloads finden Sie unter „`Provisioning von CIFS- und NFS-Dateifreigaben`“.



 a| 
`GET`
 a| 
`/datacenter/storage/aggregates`

`/datacenter/storage/aggregates/{key}`
 a| 
Mit dieser Methode können Sie die Erfassung von Aggregaten im gesamten Datacenter einsehen, um Workloads darauf bereitzustellen oder das Monitoring zu überwachen.



 a| 
`GET`
 a| 
`/datacenter/storage/luns`

`/datacenter/storage/luns/{key}`
 a| 
Mit dieser Methode können Sie die Erfassung von LUNs im gesamten Datacenter anzeigen.



 a| 
`GET`
 a| 
`/datacenter/storage/qos/policies`

`/datacenter/storage/qos/policies/{key}`
 a| 
Mithilfe dieser Methode können Sie alle Details zu allen QoS-Richtlinien im Datacenter anzeigen und die Richtlinien nach Bedarf anwenden.



 a| 
`GET`
 a| 
`/datacenter/storage/qtrees`

`/datacenter/storage/qtrees/{key}`
 a| 
Mit dieser Methode können Sie die qtree-Details im gesamten Datacenter anzeigen.



 a| 
`GET`
 a| 
`/datacenter/storage/volumes`

`/datacenter/storage/volumes/{key}`
 a| 
Mit dieser Methode können Sie die Volume-Sammlungen im Datacenter anzeigen.



 a| 
`GET`

`POST`

`DELETE`

`PATCH`
 a| 
`/datacenter/protocols/san/igroups`

`/datacenter/protocols/san/igroups/{key}`
 a| 
Sie können Initiatorgruppen zuweisen, die für den Zugriff auf bestimmte LUN-Ziele autorisiert sind. Wenn eine vorhandene Initiatorgruppe vorhanden ist, können Sie sie zuweisen. Sie können auch Initiatorgruppen erstellen und sie den LUNs zuweisen.

Sie können diese Methoden zum Abfragen, Erstellen, Löschen und Ändern von Initiatorgruppen verwenden.

Hinweise:

* `POST`: Beim Erstellen einer Initiatorgruppe können Sie die Speicher-VM angeben, auf der Sie Zugriff zuweisen möchten.
* `DELETE`: Sie müssen den igroup-Schlüssel als Eingabeparameter angeben, um eine bestimmte igroup zu löschen. Wenn Sie einer LUN bereits eine Initiatorgruppe zugewiesen haben, können Sie diese Initiatorgruppe nicht löschen.
* `PATCH`: Sie müssen den igroup-Schlüssel als Eingabeparameter angeben, um eine bestimmte igroup zu ändern. Sie müssen auch die Eigenschaft, die Sie aktualisieren möchten, zusammen mit ihrem Wert eingeben.




 a| 
`GET`

`POST`

`DELETE`

`PATCH`
 a| 
`/datacenter/svm/svms`

`/datacenter/svm/svms/{key}`
 a| 
Sie können diese Methoden verwenden, um Storage Virtual Machines (Storage VMs) anzuzeigen, zu erstellen, zu löschen und zu ändern.

Hinweise:

* `POST`: Sie müssen das Speicher-VM-Objekt eingeben, das Sie als Eingabeparameter erstellen möchten. Sie können eine benutzerdefinierte Storage-VM erstellen und anschließend erforderliche Eigenschaften zuweisen.
+

NOTE: Wenn Sie die SLO-basierte Workload-Bereitstellung auf Ihrer Umgebung aktiviert und gleichzeitig die Storage VM erstellt haben, müssen Sie sicherstellen, dass alle Protokolle unterstützt werden, die für die Bereitstellung von LUNs und Dateifreigaben erforderlich sind, z. B. SMB/CIFS, NFS, FCP Und iSCSI. Die Bereitstellungs-Workflows können fehlschlagen, wenn die Storage-VM die erforderlichen Services nicht unterstützt. Es wird empfohlen, auf der Storage-VM auch die Services für die jeweiligen Workload-Typen zu aktivieren.

* `DELETE`: Sie müssen den Speicher-VM-Schlüssel bereitstellen, um eine bestimmte Speicher-VM zu löschen.
+

NOTE: Wenn Sie die SLO-basierte Workload-Bereitstellung in Ihrer Umgebung aktiviert haben, kann diese Storage-VM nicht gelöscht werden, auf der Storage-Workloads bereitgestellt wurden. Wenn Sie eine Speicher-VM löschen, auf der ein CIFS/SMB-Server konfiguriert wurde, löscht diese API auch den CIFS/SMB-Server und die lokale Active Directory-Konfiguration. Der CIFS/SMB-Servername befindet sich jedoch weiterhin in der Active Directory-Konfiguration, die Sie manuell vom Active Directory-Server löschen müssen.

* `PATCH`: Sie müssen den Speicher-VM-Schlüssel zur Änderung einer bestimmten Speicher-VM zur Verfügung stellen. Sie müssen außerdem die Eigenschaften eingeben, die Sie aktualisieren möchten, zusammen mit ihren Werten.


|===