---
permalink: api-automation/concept-managing-fileshares-api.html 
sidebar: sidebar 
keywords:  
summary: Über die hier aufgeführten APIs können CIFS-Freigaben und NFS-Dateifreigaben angezeigt, hinzugefügt und gelöscht werden. Mithilfe dieser APIs können Sie auch die Richtlinien für Performance Service Level und Storage-Effizienz für die Dateifreigaben zuweisen und ändern. 
---
= Verwalten von Dateifreigaben
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Über die hier aufgeführten APIs können CIFS-Freigaben und NFS-Dateifreigaben angezeigt, hinzugefügt und gelöscht werden. Mithilfe dieser APIs können Sie auch die Richtlinien für Performance Service Level und Storage-Effizienz für die Dateifreigaben zuweisen und ändern.

Vor dem Zuweisen von Storage muss die Virtual Machine mit den unterstützten Protokollen erstellt und bereitgestellt werden. Ebenso müssen die Storage-Effizienz-Richtlinien für die Zuweisung von Storage-Effizienz-Richtlinien zu File Shares erstellt werden, bevor Dateifreigaben erstellt werden können.



== Anzeigen von Dateifreigaben

Anhand der folgenden Methode können Sie alle in Ihrer Unified Manager Umgebung verfügbaren Storage Workloads anzeigen. Wenn Sie ein ONTAP Cluster als Datenquelle auf Active IQ Unified Manager hinzugefügt haben, werden die Storage-Workloads für diese Cluster automatisch Ihrer Unified Manager Instanz hinzugefügt. Diese API ruft alle Dateifreigaben automatisch ab und wird manuell Ihrer Unified Manager-Instanz hinzugefügt. Sie können die Details einer bestimmten Dateifreigabe anzeigen, indem Sie diese API mit dem Dateifreigabschlüssel ausführen.

[cols="1a,1a,1a"]
|===
| Kategorie | HTTP-Verb | Pfad 


 a| 
Anbieter von Storage-Lösungen
 a| 
GET
 a| 
`/storage-provider/file-shares`

`+/storage-provider/file-shares/{key}+`

|===


== Fügen Sie Dateifreigaben hinzu

Mit der folgenden Methode können Sie CIFS- und NFS-Dateifreigaben in Ihre SVM hinzufügen. Als Eingabeparameter müssen Sie die Details der Dateifreigabe eingeben, die Sie erstellen möchten. Sie können diese API nicht zum Erstellen von FlexGroups verwenden.

[cols="1a,1a,1a"]
|===
| Kategorie | HTTP-Verb | Pfad 


 a| 
Anbieter von Storage-Lösungen
 a| 
POST
 a| 
`/storage-provider/file-shares`

|===
[NOTE]
====
Je nachdem, ob die Parameter der Zugriffssteuerungsliste (ACL) oder der Parameter für die Exportrichtlinie zur Verfügung gestellt werden, werden CIFS-Shares oder NFS-Dateifreigaben erstellt. Wenn Sie die Werte für die ACL-Parameter nicht angeben, werden CIFS-Shares nicht erstellt und NFS-Shares werden standardmäßig erstellt, um Zugriff auf alle zu ermöglichen.

====


== Löschen von Dateifreigaben

Sie können die folgende Methode verwenden, um eine bestimmte Dateifreigabe zu löschen. Zum Löschen einer bestimmten Dateifreigabe müssen Sie den Freigabeschlüssel als Eingabeparameter eingeben.

[cols="1a,1a,1a"]
|===
| Kategorie | HTTP-Verb | Pfad 


 a| 
Anbieter von Storage-Lösungen
 a| 
Löschen
 a| 
`+/storage-provider/file-shares/{key}+`

|===


== Ändern von Dateifreigaben

Sie können die folgende Methode verwenden, um eine Dateifreigabe zu ändern und deren Eigenschaften zu aktualisieren.

Sie müssen den Dateifreigabschlüssel angeben, um eine bestimmte Dateifreigabe zu ändern. Außerdem müssen Sie die Eigenschaft, die Sie aktualisieren möchten, zusammen mit ihrem Wert eingeben.

[NOTE]
====
Beachten Sie, dass Sie nur eine Eigenschaft bei einem einzelnen Aufruf dieser API aktualisieren können. Für mehrere Updates müssen Sie diese API so oft ausführen.

====
[cols="1a,1a,1a"]
|===
| Kategorie | HTTP-Verb | Pfad 


 a| 
Anbieter von Storage-Lösungen
 a| 
PATCH
 a| 
`+/storage-provider/file-shares/{key}+`

|===