---
permalink: reporting/reference-types-of-reports.html 
sidebar: sidebar 
keywords:  
summary: Eine umfassende Liste von Ansichten und Bestandsseiten, die als Berichte zur Verfügung stehen, die Sie anpassen, speichern, herunterladen und planen können. 
---
= Berichtstypen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Eine umfassende Liste von Ansichten und Bestandsseiten, die als Berichte zur Verfügung stehen, die Sie anpassen, speichern, herunterladen und planen können.



== Active IQ Unified Manager Berichte

|===
| Typ | Storage oder Netzwerkobjekt 


 a| 
Kapazität
 a| 
Cluster

Aggregate

Volumes

Qtrees



 a| 
Systemzustand
 a| 
Cluster

Knoten

Aggregate

Storage-VMs

Volumes

SMB/CIFS-Freigaben

NFS-Freigaben



 a| 
Leistung
 a| 
Cluster

Knoten

Aggregate

Storage-VMs

Volumes

LUNs

NVMe Namespaces

Netzwerkschnittstellen (LIFs)

Ports



 a| 
Quality of Service
 a| 
Herkömmliche QoS-Richtliniengruppen

Adaptive QoS-Richtliniengruppen

Gruppen für Leistungszielgruppen



 a| 
Volume-Sicherungsbeziehungen (verfügbar auf der Seite Volumes)
 a| 
Alle Beziehungen

Transferstatus der letzten 1 Monate

Letzte 1 Monat Transferrate

|===