---
permalink: performance-checker/reference-what-data-does-the-workload-analyzer-display.html 
sidebar: sidebar 
keywords: workload analyzer charts 
summary: Die Seite Workload Analyzer enthält Informationen zu aktuellen Ereignissen, die Auswirkungen auf den Workload haben könnten, Empfehlungen zur potenziellen Behebung des Ereignisses und Diagramme zur Analyse des Performance- und Kapazitätsverlaufs. 
---
= Welche Daten werden vom Workload Analyzer angezeigt
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Seite Workload Analyzer enthält Informationen zu aktuellen Ereignissen, die Auswirkungen auf den Workload haben könnten, Empfehlungen zur potenziellen Behebung des Ereignisses und Diagramme zur Analyse des Performance- und Kapazitätsverlaufs.

Oben auf der Seite geben Sie den Namen des Workloads (Volume oder LUN) an, den Sie analysieren möchten, und den Zeitrahmen, über den Sie Statistiken anzeigen möchten. Sie können den Zeitrahmen jederzeit ändern, wenn Sie einen kürzeren oder längeren Zeitraum anzeigen möchten.

In den anderen Bereichen der Seite werden die Analyseergebnisse sowie die Performance- und Kapazitätsdiagramme angezeigt.

[NOTE]
====
Workload-Diagramme für LUNs bieten nicht dasselbe Maß an Statistiken wie die Diagramme für Volumes. Daher werden bei der Analyse dieser beiden Workload-Typen Unterschiede feststellen.

====
* *Veranstaltungsübersicht*
+
Zeigt eine kurze Übersicht über Anzahl und Art der Ereignisse an, die im Laufe des Zeitraums aufgetreten sind. Wenn Ereignisse aus unterschiedlichen Wirkungsbereichen vorliegen (z. B. Leistung und Kapazität), werden diese Informationen angezeigt, sodass Sie Details für den gewünschten Ereignistyp auswählen können. Klicken Sie auf den Ereignistyp, um eine Liste der Ereignisnamen anzuzeigen.

+
Wenn während des Zeitraums nur ein Ereignis auftritt, wird für einige Ereignisse eine Liste mit Empfehlungen zur Behebung des Problems aufgeführt.

* *Veranstaltungstermine*
+
Zeigt alle Vorkommen von Ereignissen während des angegebenen Zeitraums an. Bewegen Sie den Cursor über jedes Ereignis, um den Ereignisnamen anzuzeigen.

+
Wenn Sie auf dieser Seite angekommen sind, indem Sie auf der Seite Ereignisdetails auf die Schaltfläche *Workload analysieren* klicken, erscheint das Symbol für das ausgewählte Ereignis größer, sodass Sie das Ereignis identifizieren können.

* *Bereich der Performance-Diagramme*
+
Zeigt Diagramme für Latenz, Durchsatz (sowohl IOPS als auch MB/s) und Auslastung (sowohl für den Node als auch für das Aggregat) basierend auf dem ausgewählten Zeitraum an. Sie können auf den Link Performance-Details anzeigen klicken, um die Seite im Performance Explorer für den Workload anzuzeigen, falls Sie eine weitere Analyse durchführen möchten.

+
** *Latenz* zeigt die Latenz für den Workload an. Das Diagramm enthält drei Ansichten, mit denen Sie die gesamte Latenz, die Latenz, aufgeschlüsselt nach „Lesen“, „Schreiben“ und „anderen Prozessen“ sowie die nach Cluster-Komponente durchbrochene Latenz sehen können.
+
Siehe link:concept-cluster-components-and-why-they-can-be-in-contention.adoc["Cluster-Komponenten und warum sie über Konflikte verfügen können"] Eine Beschreibung der hier angezeigten Cluster-Komponenten.

** *Throughput* zeigt IOPS und MB/s Durchsatz für den Workload an. Das Diagramm verfügt über zwei Ansichten, mit denen Sie den Gesamtdurchsatz und den Durchsatz, der durch Lesen, Schreiben und andere Prozesse aufgeschlüsselt wird, anzeigen können.
+
Dieses Diagramm zeigt auch Quality of Service (QoS) Einstellungen für maximale und minimale Durchsatzschwellenwerte an, falls konfiguriert. Damit sehen Sie, wo das System den Durchsatz absichtlich begrenzt.

** *Auslastung* zeigt die Auslastung sowohl für das Aggregat als auch für den Knoten an, auf dem der Workload ausgeführt wird. Von hier aus sehen Sie, ob Ihr Aggregat oder die Knoten überausgelastet sind, was zu hoher Latenz führt. Bei der Analyse von FlexGroup Volumes werden in den Nutzungsdiagrammen mehrere Nodes und mehrere Aggregate aufgeführt.


* *Kapazität Diagrammbereich*
+
Zeigt Diagramme für die Datenkapazität und Snapshot-Kapazität der letzten einen Monat für den Workload an.

+
Bei Volumes können Sie über den Link Kapazitätsdetails anzeigen auf die Seite Integritätsdetails für den Workload anzeigen klicken, falls Sie weitere Analysen durchführen möchten. LUNs stellen diesen Link nicht bereit, da für LUNs keine Seite „Integritätsdetails“ vorhanden ist.

+
** *Kapazitätsansicht* zeigt den gesamten verfügbaren Speicherplatz an, der für den Workload und den logischen genutzten Speicherplatz zugewiesen ist (nach allen NetApp Optimierungen).
** *Snapshot View* zeigt den gesamten reservierten Speicherplatz für Snapshot Kopien und die Menge des derzeit genutzten Speicherplatzes an. Beachten Sie, dass LUNs keine Snapshot-Ansicht bereitstellen. Beide Diagramme enthalten eine Schätzung der verbleibenden Zeit, bevor die Kapazität für diesen Workload voll ist. Diese Informationen basieren auf historischer Nutzung und erfordern mindestens 10 Tage Daten. Wenn die Kapazität weniger als 30 Tage verbleibt, identifiziert Unified Manager den Storage als „`nahezu voll`“.



