---
permalink: install-windows/task-changing-the-jboss-password-on-windows.html 
sidebar: sidebar 
keywords:  
summary: Sie können ein neues, benutzerdefiniertes JBoss-Kennwort erstellen, um das bei der Installation festgelegte Standardpasswort zu überschreiben. Diese Aufgabe ist optional, aber an einigen Standorten muss diese Sicherheitsfunktion möglicherweise die Standardeinstellung für die Unified Manager-Installation außer Kraft setzen. Dieser Vorgang ändert auch das Passwort, das JBoss zum Zugriff auf MySQL verwendet. 
---
= Ändern des JBoss-Passworts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein neues, benutzerdefiniertes JBoss-Kennwort erstellen, um das bei der Installation festgelegte Standardpasswort zu überschreiben. Diese Aufgabe ist optional, aber an einigen Standorten muss diese Sicherheitsfunktion möglicherweise die Standardeinstellung für die Unified Manager-Installation außer Kraft setzen. Dieser Vorgang ändert auch das Passwort, das JBoss zum Zugriff auf MySQL verwendet.



== Bevor Sie beginnen

* Sie müssen über Windows-Administratorrechte für das System verfügen, auf dem Unified Manager installiert ist.
* Sie müssen das Passwort für den MySQL-Root-Benutzer besitzen.
* Sie müssen auf die von NetApp bereitgestellte Lösung zugreifen können `password.bat` Skript im Verzeichnis `\Program Files\NetApp\essentials\bin`.




== Schritte

. Melden Sie sich als Admin-Benutzer auf der Unified Manager-Host-Maschine an.
. Beenden Sie mithilfe der Windows Services-Konsole die folgenden Unified Manager-Services:
+
** Erwerbsservice für NetApp Active IQ (Ozie-au)
** NetApp Active IQ Management Server-Service (OnCommandsvc)


. Starten Sie den `password.bat` Skript zum Starten des Passwortänderungsprozesses: `C:\Program Files\NetApp\essentials\bin> password.bat resetJBossPassword`
. Geben Sie bei entsprechender Aufforderung das Passwort für den Benutzer MySQL Root ein.
. Geben Sie bei entsprechender Aufforderung das aktuelle JBoss-Benutzerpasswort ein.
+
Das Standardpasswort lautet `D11h1aMu@79%`.

. Geben Sie bei Aufforderung das neue JBoss-Benutzerpasswort ein, und geben Sie es zur Bestätigung erneut ein.
+
Die Bestätigungsmeldungen werden angezeigt, wenn die Änderungen vorgenommen werden, und Sie werden zum letzten Mal aufgefordert, das neue JBoss-Benutzerpasswort einzugeben.

. Geben Sie noch einmal das neue JBoss-Benutzerpasswort ein.
. Starten Sie nach Abschluss des Skripts die Unified Manager-Dienste über die Windows-Dienstkonsole:
+
** NetApp Active IQ Management Server-Service (OnCommandsvc)
** Erwerbsservice für NetApp Active IQ (Ozie-au)


. Nachdem alle Services gestartet wurden, können Sie sich in der UI von Unified Manager einloggen.

