---
permalink: install-windows/task-upgrading-to-unified-manager-on-microsoft-windows.html 
sidebar: sidebar 
keywords:  
summary: Sie können ein Upgrade von Unified Manager 9.5 oder 9.6 auf 9.7 durchführen, indem Sie die Installationsdatei auf der Windows-Plattform herunterladen und ausführen. 
---
= Upgrade Von Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Upgrade von Unified Manager 9.5 oder 9.6 auf 9.7 durchführen, indem Sie die Installationsdatei auf der Windows-Plattform herunterladen und ausführen.



== Bevor Sie beginnen

* Das System, auf dem Unified Manager aktualisiert wird, muss die System- und Software-Anforderungen erfüllen.
+
xref:concept-virtual-infrastructure-or-hardware-system-requirements.adoc[Hardwaresystemanforderungen]

+
xref:reference-windows-software-and-installation-requirements.adoc[Windows Software- und Installationsanforderungen]

+
[NOTE]
====
Ab Unified Manager 9.5 wird OpenJDK im Installationspaket bereitgestellt und automatisch installiert. Oracle Java wird ab Unified Manager 9.5 nicht unterstützt.

====
+
[NOTE]
====
Ab Unified Manager 9.4 ist Microsoft .NET 4.5.2 oder höher erforderlich. Stellen Sie sicher, dass Sie die richtige Version von .NET installiert haben, bevor Sie das Upgrade starten.

====
* Sie müssen über Administratorrechte für Windows verfügen. Stellen Sie sicher, dass Ihr Benutzername nicht mit einem Ausrufezeichen "` beginnt!`". Installation of Unified Manager might fail if the user name of user running the installation begins with "`!`".
* Zur Anmeldung auf der NetApp Support Site müssen Sie über gültige Zugangsdaten verfügen.
* Um Datenverlust zu vermeiden, müssen Sie ein Backup des Unified Manager-Rechners erstellt haben, falls während des Upgrades ein Problem auftritt.
* Sie müssen über ausreichend Speicherplatz verfügen, um das Upgrade durchführen zu können.
+
Der verfügbare Speicherplatz auf dem Installationslaufwerk muss 2.5 GB größer sein als die Größe des Datenverzeichnisses. Das Upgrade wird angehalten und es wird eine Fehlermeldung angezeigt, die angibt, wie viel Speicherplatz hinzugefügt werden soll, wenn nicht genügend freier Speicherplatz vorhanden ist.

* Während des Upgrades werden Sie möglicherweise aufgefordert zu bestätigen, ob Sie die vorherigen Standardeinstellungen für die Aufbewahrung von Performancedaten für 13 Monate beibehalten oder in 6 Monate ändern möchten. Nach der Bestätigung werden die historischen Leistungsdaten nach 6 Monaten gelöscht.
* Vor dem Upgrade müssen Sie alle offenen Dateien oder Ordner in schließen `<InstallDir\>\JDK` Und `MySQL Data Directory`.




== Über diese Aufgabe

Während des Upgrades ist Unified Manager nicht verfügbar. Vor dem Upgrade von Unified Manager sollten alle laufenden Vorgänge abgeschlossen werden.

Wenn Unified Manager mit einer Instanz von OnCommand Workflow Automation gekoppelt ist und für beide Produkte neue Versionen der Software zur Verfügung stehen, müssen Sie die beiden Produkte trennen und anschließend eine neue Workflow-Automatisierungsverbindung einrichten, nachdem Sie die Upgrades durchgeführt haben. Wenn Sie ein Upgrade auf nur eines der Produkte durchführen, müssen Sie sich nach dem Upgrade bei Workflow Automation anmelden und überprüfen, ob noch Daten von Unified Manager erfasst werden.



== Schritte

. Melden Sie sich auf der NetApp Support Site an und suchen Sie die Seite *Download* für die Installation von Unified Manager auf der Windows Plattform.
+
https://mysupport.netapp.com/products/index.html[]

. Laden Sie die Windows-Installationsdatei von Unified Manager in ein Zielverzeichnis im Windows-System herunter.
. Klicken Sie mit der rechten Maustaste, und führen Sie die ausführbare Datei für das Unified Manager-Installationsprogramm aus `(.exe)` Datei als Administrator ausführen.
+
Unified Manager fordert Sie zur folgenden Meldung auf:

+
[listing]
----
This setup will perform an upgrade of Unified Manager. Do you want to continue?
----
. Klicken Sie auf *Ja* und dann auf *Weiter*.
. Geben Sie das bei der Installation festgelegte MySQL8-Root-Passwort ein, und klicken Sie dann auf *Weiter*.
. Melden Sie sich in der Web-UI von Unified Manager an und überprüfen Sie die Versionsnummer.




== Nachdem Sie fertig sind

[NOTE]
====
Führen Sie den folgenden Befehl aus, um eine stille Aktualisierung von Unified Manager durchzuführen: `ActiveIQUnifiedManager-<version\>.exe /s /v"MYSQL_PASSWORD=netapp21! /qn /l*v C:\install.log`

====