---
permalink: config/task-configuring-event-notification-settings.html 
sidebar: sidebar 
keywords:  
summary: Sie können Unified Manager so konfigurieren, dass Benachrichtigungen gesendet werden, wenn ein Ereignis generiert wird oder ein Ereignis einem Benutzer zugewiesen ist. Sie können den SMTP-Server konfigurieren, der zum Senden der Warnmeldung verwendet wird, und Sie können verschiedene Benachrichtigungsmechanismen festlegen. So können beispielsweise Warnmeldungen als E-Mails oder SNMP-Traps gesendet werden. 
---
= Konfigurieren von Einstellungen für Ereignisbenachrichtigungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können Unified Manager so konfigurieren, dass Benachrichtigungen gesendet werden, wenn ein Ereignis generiert wird oder ein Ereignis einem Benutzer zugewiesen ist. Sie können den SMTP-Server konfigurieren, der zum Senden der Warnmeldung verwendet wird, und Sie können verschiedene Benachrichtigungsmechanismen festlegen – beispielsweise können Alarmbenachrichtigungen als E-Mails oder SNMP-Traps gesendet werden.



== Bevor Sie beginnen

Sie müssen die folgenden Informationen haben:

* E-Mail-Adresse, von der die Benachrichtigung gesendet wird
+
Die E-Mail-Adresse wird im Feld „`von`“ in gesendeten Warnmeldungen angezeigt. Falls die E-Mail aus irgendeinem Grund nicht zugestellt werden kann, wird diese E-Mail-Adresse auch als Empfänger für nicht lieferbare E-Mails verwendet.

* Hostname des SMTP-Servers sowie Benutzername und Kennwort für den Zugriff auf den Server
* Hostname oder IP-Adresse für den Trap-Ziel-Host, der den SNMP-Trap empfängt, zusammen mit der SNMP-Version, dem Outbound-Trap-Port, der Community und anderen erforderlichen SNMP-Konfigurationswerten
+
Um mehrere Trap-Ziele festzulegen, trennen Sie jeden Host durch ein Komma. In diesem Fall müssen alle anderen SNMP-Einstellungen, wie Version und Outbound-Trap-Port, für alle Hosts in der Liste identisch sein.



Sie müssen über die Rolle „Anwendungsadministrator“ oder „Speicheradministrator“ verfügen.



== Schritte

. Klicken Sie im linken Navigationsbereich auf *Allgemein* > *Benachrichtigungen*.
. Konfigurieren Sie auf der Seite *Benachrichtigungen* die entsprechenden Einstellungen und klicken Sie auf *Speichern*.
+
[NOTE]
====
....
**If the From Address is pre-filled with the address "ActiveIQUnifiedManager@localhost.com", you should change it to a real, working email address to make sure that all email notifications are delivered successfully.
** If the host name of the SMTP server cannot be resolved, you can specify the IP address (IPv4 or IPv6) of the SMTP server instead of the host name.
....
====

